#! /bin/bash

sleep 1
[ -v CONTENT_LENGTH ] && read -N $CONTENT_LENGTH message_body
echo "$TCPREMOTEIP:`date +%s`:$message_body" >> /var/lib/cha/chosed.txt
echo 'HTTP/1.1 201 Created'
echo 'Content-Type: text/plain'
echo ''
